In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [7]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Ananya\Downloads\pd_speech_features.csv (1).zip')
df.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

In [19]:
X = df.drop(['id', 'gender'], axis=1)
y = df['gender']

In [49]:
df.head()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
0,0,1,0.85247,0.71826,0.57227,240,239,0.008064,0.000087,0.00218,...,1.5620,2.6445,3.8686,4.2105,5.1221,4.4625,2.6202,3.0004,18.9405,1
1,0,1,0.76686,0.69481,0.53966,234,233,0.008258,0.000073,0.00195,...,1.5589,3.6107,23.5155,14.1962,11.0261,9.5082,6.5245,6.3431,45.1780,1
2,0,1,0.85083,0.67604,0.58982,232,231,0.008340,0.000060,0.00176,...,1.5643,2.3308,9.4959,10.7458,11.0177,4.8066,2.9199,3.1495,4.7666,1
3,1,0,0.41121,0.79672,0.59257,178,177,0.010858,0.000183,0.00419,...,3.7805,3.5664,5.2558,14.0403,4.2235,4.6857,4.8460,6.2650,4.0603,1
4,1,0,0.32790,0.79782,0.53028,236,235,0.008162,0.002669,0.00535,...,6.1727,5.8416,6.0805,5.7621,7.7817,11.6891,8.2103,5.0559,6.1164,1

In [29]:
df.tail()

,id,gender,PPE,DFA,RPDE,numPulses,numPeriodsPulses,meanPeriodPulses,stdDevPeriodPulses,locPctJitter,...,tqwt_kurtosisValue_dec_28,tqwt_kurtosisValue_dec_29,tqwt_kurtosisValue_dec_30,tqwt_kurtosisValue_dec_31,tqwt_kurtosisValue_dec_32,tqwt_kurtosisValue_dec_33,tqwt_kurtosisValue_dec_34,tqwt_kurtosisValue_dec_35,tqwt_kurtosisValue_dec_36,class
751,250,0,0.80903,0.56355,0.28385,417,416,0.004627,0.000052,0.00064,...,3.0706,3.0190,3.1212,2.4921,3.5844,3.5400,3.3805,3.2003,6.8671,0
752,250,0,0.16084,0.56499,0.59194,415,413,0.004550,0.000220,0.00143,...,1.9704,1.7451,1.8277,2.4976,5.2981,4.2616,6.3042,10.9058,28.4170,0
753,251,0,0.88389,0.72335,0.46815,381,380,0.005069,0.000103,0.00076,...,51.5607,44.4641,26.1586,6.3076,2.8601,2.5361,3.5377,3.3545,5.0424,0
754,251,0,0.83782,0.74890,0.49823,340,339,0.005679,0.000055,0.00092,...,19.1607,12.8312,8.9434,2.2044,1.9496,1.9664,2.6801,2.8332,3.7131,0
755,251,0,0.81304,0.76471,0.46374,340,339,0.005676,0.000037,0.00078,...,62.9927,21.8152,9.2457,4.8555,3.0551,3.0415,4.0116,2.6217,3.1527,0

In [39]:
df.shape

(756, 755)

In [53]:
print(df.columns)

Index(['id', 'gender', 'PPE', 'DFA', 'RPDE', 'numPulses', 'numPeriodsPulses',
       'meanPeriodPulses', 'stdDevPeriodPulses', 'locPctJitter',
       ...
       'tqwt_kurtosisValue_dec_28', 'tqwt_kurtosisValue_dec_29',
       'tqwt_kurtosisValue_dec_30', 'tqwt_kurtosisValue_dec_31',
       'tqwt_kurtosisValue_dec_32', 'tqwt_kurtosisValue_dec_33',
       'tqwt_kurtosisValue_dec_34', 'tqwt_kurtosisValue_dec_35',
       'tqwt_kurtosisValue_dec_36', 'class'],
      dtype='object', length=755)

In [57]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [59]:
print("Before scaling:")
print(X.head())

print("\nAfter scaling:")
print(X_scaled[:5])

Before scaling:
   id  gender     RPDE  numPulses  numPeriodsPulses  meanPeriodPulses  \
0   0       1  0.57227        240               239          0.008064
1   0       1  0.53966        234               233          0.008258
2   0       1  0.58982        232               231          0.008340
3   1       0  0.59257        178               177          0.010858
4   1       0  0.53028        236               235          0.008162

   stdDevPeriodPulses  locPctJitter  locAbsJitter  rapJitter  ...  \
0            0.000087       0.00218      0.000018    0.00067  ...
1            0.000073       0.00195      0.000016    0.00052  ...
2            0.000060       0.00176      0.000015    0.00057  ...
3            0.000183       0.00419      0.000046    0.00149  ...
4            0.002669       0.00535      0.000044    0.00166  ...

   tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                     1.5620                     2.6445
1                     1.5589                     3.6107
2                     1.5643                     2.3308
3                     3.7805                     3.5664
4                     6.1727                     5.8416

   tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                     3.8686                     4.2105
1                    23.5155                    14.1962
2                     9.4959                    10.7458
3                     5.2558                    14.0403
4                     6.0805                     5.7621

   tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                     5.1221                     4.4625
1                    11.0261                     9.5082
2                    11.0177                     4.8066
3                     4.2235                     4.6857
4                     7.7817                    11.6891

   tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                     2.6202                     3.0004
1                     6.5245                     6.3431
2                     2.9199                     3.1495
3                     4.8460                     6.2650
4                     8.2103                     5.0559

   tqwt_kurtosisValue_dec_36  class
0                    18.9405      1
1                    45.1780      1
2                     4.7666      1
3                     4.0603      1
4                     6.1164      1

[5 rows x 753 columns]

After scaling:
[[-1.72519117  0.96874225  0.60583513 ... -0.81472704 -0.36659507
   0.58345997]
 [-1.72519117  0.96874225  0.36841516 ... -0.58297219  0.40039616
   0.58345997]
 [-1.72519117  0.96874225  0.73360944 ... -0.8043897  -0.7809355
   0.58345997]
 [-1.71144463 -1.03226633  0.75363106 ... -0.58838699 -0.80158251
   0.58345997]
 [-1.71144463 -1.03226633  0.30012325 ... -0.67221587 -0.74147729
   0.58345997]]

In [61]:
print("Mean after scaling:", X_scaled.mean(axis=0))
print("Std after scaling:", X_scaled.std(axis=0))

Mean after scaling: [ 0.00000000e+00 -1.97372982e-16 -2.81961403e-17 -6.57909941e-17
 -1.69176842e-16 -1.22183275e-16  3.75948537e-17  1.87974269e-17
 -1.12784561e-16  6.10916373e-17 -4.69935672e-18  9.39871344e-18
 -5.40426023e-17 -2.34967836e-17  1.87974269e-17  8.92877776e-17
 -2.81961403e-16  5.87419590e-17 -9.63368127e-16 -1.40980702e-17
  2.49065906e-16 -1.01036169e-16  9.70417162e-16  4.13543391e-16
 -4.69935672e-18  6.76707367e-16 -2.86660760e-16  2.44366549e-16
 -1.40980702e-17 -4.46438888e-17  6.10916373e-17 -7.04903508e-17
 -6.81406724e-16 -1.87974269e-17 -4.69935672e-18  9.39871344e-17
  1.43330380e-16 -9.86864911e-17 -3.38353684e-16  5.59223449e-16
  1.56018643e-15 -5.16929239e-17 -1.22183275e-16  2.34967836e-17
 -1.50379415e-16  3.28954970e-17  1.35341473e-15  7.75393858e-16
  2.58464619e-17  3.05458187e-17  4.22942105e-17  4.82858903e-16
 -1.12784561e-16  3.87696929e-16 -1.72466392e-15  0.00000000e+00
  1.02915912e-15 -9.39871344e-18 -4.69935672e-18 -3.99445321e-17
  1.87974269e-17 -2.16170409e-16 -1.87974269e-17  9.39871344e-18
 -1.17483918e-18  8.45884209e-17  1.11609722e-17  9.39871344e-18
  0.00000000e+00  4.69935672e-17  0.00000000e+00  9.39871344e-18
 -1.87974269e-17  4.69935672e-18  7.04903508e-18 -3.17206578e-17
  2.23219444e-17  2.11471052e-17  9.39871344e-18 -1.40980702e-17
  7.04903508e-18  4.69935672e-18 -9.39871344e-18  1.87974269e-17
 -1.40980702e-17 -2.70213011e-17 -4.69935672e-18 -5.87419590e-18
  0.00000000e+00 -1.87974269e-17  0.00000000e+00 -1.87974269e-17
  5.87419590e-18  9.39871344e-18 -2.46716228e-17 -2.34967836e-17
 -6.57909941e-17 -6.57909941e-17 -2.49065906e-16 -1.73876199e-16
 -3.14856900e-16  7.51897075e-17 -1.17483918e-16 -1.71526520e-16
 -1.76225877e-17  1.01036169e-16  2.34967836e-17  6.57909941e-17
  1.99722661e-16  9.86864911e-17 -1.12784561e-16 -1.71526520e-16
  5.16929239e-17 -2.58464619e-17 -1.50379415e-16 -8.92877776e-17
 -2.16170409e-16  3.75948537e-17 -1.24532953e-16 -3.28954970e-16
 -3.18381418e-16 -6.57909941e-17 -1.96198143e-16 -7.51897075e-17
  5.63922806e-17  7.51897075e-17 -1.08085205e-16  4.08844034e-16
 -2.25569122e-16  2.34967836e-16 -1.01036169e-16 -2.11471052e-16
  7.51897075e-17  3.94745964e-16 -2.81961403e-17 -1.97372982e-16
  4.27641461e-16  5.82720233e-16 -1.52893571e-14  1.87974269e-17
  0.00000000e+00  0.00000000e+00 -1.17483918e-17  9.39871344e-18
  7.04903508e-18 -8.22387426e-18 -6.10916373e-17  4.69935672e-18
  2.81961403e-17  1.40980702e-17  1.87974269e-17 -9.39871344e-18
  2.34967836e-17 -9.39871344e-18  2.81961403e-17 -4.69935672e-18
  1.17483918e-17  2.11471052e-17 -2.81961403e-17  2.39667193e-16
 -4.22942105e-17  9.39871344e-18 -8.22387426e-17  9.39871344e-18
  2.34967836e-17 -2.34967836e-17 -3.52451754e-17  2.34967836e-17
 -6.57909941e-17 -4.69935672e-18  1.87974269e-17  9.39871344e-18
  3.99445321e-17 -4.69935672e-18  2.34967836e-17 -3.99445321e-17
 -2.34967836e-18 -5.87419590e-17  1.87974269e-17  0.00000000e+00
 -3.52451754e-17  3.75948537e-17  1.17483918e-17  9.39871344e-18
 -1.17483918e-17 -9.39871344e-18  1.17483918e-17  2.11471052e-17
  0.00000000e+00 -9.39871344e-18 -1.03385848e-16  2.34967836e-17
 -7.98890642e-17 -1.31581988e-16 -8.45884209e-17  1.40980702e-17
  5.16929239e-17  9.86864911e-17  1.87974269e-17  7.19001578e-16
 -7.51897075e-17  3.94745964e-16  8.22387426e-16 -2.28858672e-15
 -1.17483918e-16  4.66646122e-15 -2.69273140e-15 -1.69646778e-15
 -4.32340818e-15 -2.34967836e-17 -5.63922806e-17  3.28954970e-17
  1.22183275e-16  7.98890642e-17  0.00000000e+00  9.39871344e-18
  6.57909941e-17  5.16929239e-17 -1.12784561e-16 -8.45884209e-17
  9.39871344e-18  7.51897075e-17  7.98890642e-17 -1.59778128e-16
 -9.39871344e-17 -4.22942105e-17  2.49065906e-16  2.86660760e-16
 -1.97372982e-16 -1.13090254e-12  2.34967836e-17 -4.69935672e-18
 -3.52451754e-17 -4.69935672e-18 -4.69935672e-18  7.04903508e-18
  9.39871344e-18  9.39871344e-18  7.04903508e-18 -1.40980702e-17
 -7.04903508e-18 -1.17483918e-17 -3.75948537e-17  7.04903508e-18
 -9.39871344e-18  0.00000000e+00 -1.29232310e-17 -9.39871344e-18
  1.05735526e-17  9.39871344e-18  3.57151111e-16 -1.24063017e-15
 -1.55078772e-16 -4.04144678e-16 -2.11471052e-16  6.76707367e-16
 -5.38076344e-16 -6.57909941e-17  4.65236315e-16  2.49065906e-16
  4.69935672e-18 -2.58464619e-17  2.34967836e-17 -1.87974269e-17
  2.81961403e-17  3.52451754e-18  3.81822733e-17 -3.52451754e-17
 -2.34967836e-17 -9.39871344e-18  1.87974269e-17  3.52451754e-17
  9.39871344e-18  7.04903508e-18  7.04903508e-18 -1.29232310e-17
 -4.69935672e-18  1.87974269e-17 -5.16929239e-17  1.40980702e-17
  9.86864911e-17  1.92673625e-16 -3.38353684e-16  1.03385848e-16
  1.87974269e-17  1.36281345e-16 -9.86864911e-17  3.57151111e-16
  9.39871344e-17  3.43053040e-16 -7.47197718e-16 -9.58668770e-16
  2.43896614e-15  1.33461731e-15 -3.55271368e-15 -5.36196602e-15
 -1.02586957e-14 -4.60536958e-15  6.69658332e-15 -5.29617502e-15
 -1.07145333e-15 -2.30268479e-16 -4.79334385e-16  9.77466197e-16
 -7.94191285e-16  8.22387426e-16  3.94745964e-16 -6.62609297e-16
 -8.97577133e-16 -9.02276490e-16 -3.10157543e-16 -7.70694502e-16
  3.75948537e-16 -5.12229882e-16  2.25099187e-15  7.23700935e-16
 -2.67863333e-16 -1.36281345e-16  8.27086782e-16 -1.40980702e-16
 -2.81961403e-17 -2.11471052e-17  2.34967836e-18  5.87419590e-18
  1.87974269e-17 -9.39871344e-18 -5.63922806e-17  1.03385848e-16
 -9.39871344e-18 -1.87974269e-17  9.39871344e-18  5.63922806e-17
  5.40426023e-17 -5.28677631e-17  4.69935672e-18  1.87974269e-17
  4.22942105e-17  1.87974269e-16 -1.15134240e-16  1.87974269e-17
  7.04903508e-17  1.08085205e-16 -3.52451754e-17 -2.34967836e-17
  9.63368127e-17  4.46438888e-17  9.39871344e-18  0.00000000e+00
  1.87974269e-17 -2.34967836e-17 -2.81961403e-17  9.39871344e-18
  0.00000000e+00  1.87974269e-17  0.00000000e+00  0.00000000e+00
 -7.04903508e-17  4.46438888e-17  2.34967836e-17  9.39871344e-18
  9.39871344e-18 -5.63922806e-17  5.16929239e-17 -5.63922806e-17
  2.81961403e-17  7.51897075e-17 -3.05458187e-17 -3.28954970e-17
  7.04903508e-17  5.75671198e-17 -9.63368127e-17 -1.28057471e-16
  9.39871344e-17 -2.63163976e-16  4.69935672e-17  1.31581988e-16
 -1.45680058e-16 -1.38631023e-16 -2.81961403e-17 -4.22942105e-17
 -1.40980702e-17  1.40980702e-17  1.87974269e-17 -9.39871344e-18
 -4.69935672e-18  1.05735526e-17 -1.12784561e-16  0.00000000e+00
  5.28677631e-18  1.87974269e-17 -9.39871344e-18  9.39871344e-18
 -3.19556257e-16  1.97372982e-16 -5.59223449e-16  1.50379415e-16
 -2.91360117e-16  3.24255614e-16 -3.10157543e-16 -5.92118946e-16
  1.87974269e-16  1.22183275e-16  7.42498361e-16 -8.45884209e-17
 -5.63922806e-17 -9.63368127e-17 -9.63368127e-17 -1.69176842e-16
 -1.15134240e-16 -1.87974269e-17 -3.75948537e-17 -2.25569122e-16
  1.03385848e-16  1.85624590e-16 -2.11471052e-16  8.45884209e-17
 -3.28954970e-17 -2.23219444e-16 -2.65513655e-16  2.34967836e-16
  4.37040175e-16 -1.97372982e-16  1.22183275e-16 -1.12784561e-16
 -1.12784561e-16  3.66549824e-16  7.51897075e-17 -9.39871344e-18
  1.87974269e-17 -4.93432455e-17 -2.34967836e-17  7.28400291e-17
  1.40980702e-17  0.00000000e+00 -4.69935672e-18  7.51897075e-17
 -8.45884209e-17  2.81961403e-17  1.64477485e-17 -5.40426023e-17
  3.52451754e-17 -6.81406724e-17  3.28954970e-17  1.40980702e-17
  9.39871344e-17  2.81961403e-17  2.11471052e-17  5.63922806e-17
 -3.99445321e-17  4.22942105e-17  3.75948537e-17  5.52174414e-17
 -4.69935672e-18  5.87419590e-17 -1.64477485e-17  2.34967836e-17
 -9.39871344e-18  0.00000000e+00 -2.81961403e-17 -1.87974269e-17
  0.00000000e+00  1.87974269e-17  9.39871344e-18 -1.87974269e-17
  5.63922806e-17 -3.05458187e-17 -4.93432455e-17 -4.69935672e-18
 -4.69935672e-18 -1.40980702e-17  1.40980702e-17  3.75948537e-17
  9.39871344e-18 -7.51897075e-17 -5.16929239e-17  2.81961403e-17
  5.87419590e-17  1.64477485e-17 -7.75393858e-17  1.24532953e-16
 -7.51897075e-17  4.69935672e-18  0.00000000e+00 -6.10916373e-17
  2.34967836e-17  7.28400291e-17 -4.46438888e-17 -1.64477485e-17
 -5.40426023e-17  1.87974269e-17 -1.87974269e-17  4.69935672e-18
 -9.39871344e-18  9.39871344e-18  3.28954970e-17  4.69935672e-18
 -9.39871344e-18 -4.69935672e-18  9.39871344e-18  1.87974269e-17
 -7.04903508e-18  9.39871344e-18  7.04903508e-18 -9.39871344e-18
  0.00000000e+00  7.04903508e-18 -2.34967836e-18  0.00000000e+00
 -1.17483918e-17  0.00000000e+00 -8.22387426e-18 -1.05735526e-17
  1.52729093e-17 -1.17483918e-17  9.39871344e-18 -2.46716228e-17
  1.87974269e-17 -8.22387426e-18  0.00000000e+00  0.00000000e+00
  3.52451754e-18  4.69935672e-18  1.17483918e-18 -7.04903508e-18
 -1.40980702e-17 -2.34967836e-18 -4.69935672e-18 -9.39871344e-18
 -9.39871344e-18 -1.17483918e-17  1.29232310e-17 -1.52729093e-17
 -2.34967836e-18 -1.17483918e-17 -7.04903508e-18  4.46438888e-17
  7.04903508e-18  9.39871344e-18 -9.39871344e-18  2.34967836e-17
  1.40980702e-17  2.34967836e-18  1.17483918e-17  5.87419590e-18
 -8.22387426e-18  0.00000000e+00  4.69935672e-18 -1.29232310e-17
  2.34967836e-17  1.40980702e-17  0.00000000e+00 -5.87419590e-18
  1.40980702e-17 -2.34967836e-18 -9.39871344e-18 -2.34967836e-18
  4.69935672e-18 -1.64477485e-17 -1.17483918e-18  1.40980702e-17
  1.29232310e-17  2.34967836e-17 -1.17483918e-18 -2.11471052e-17
 -4.69935672e-18 -1.93848465e-17 -1.64477485e-17 -4.69935672e-18
 -9.39871344e-18  0.00000000e+00  7.04903508e-18 -1.64477485e-17
  3.28954970e-17 -1.17483918e-17 -1.17483918e-16 -7.98890642e-17
 -1.59778128e-16 -9.39871344e-17 -1.73876199e-16 -1.69176842e-16
  1.22183275e-16 -5.63922806e-17  4.69935672e-18 -7.98890642e-17
 -1.40980702e-16  2.11471052e-17  3.17206578e-17 -1.56253611e-16
 -7.28400291e-17  1.69176842e-16  0.00000000e+00  1.50379415e-16
  1.33931666e-16  8.10639034e-17  6.57909941e-17 -2.81961403e-17
  2.11471052e-17 -7.98890642e-17  0.00000000e+00  2.34967836e-17
  4.22942105e-17  2.81961403e-17  2.81961403e-17  1.87974269e-17
 -9.39871344e-18  1.87974269e-17  5.63922806e-17 -2.81961403e-17
  1.03385848e-16  7.51897075e-17 -1.45680058e-16  9.39871344e-17
  7.98890642e-17  6.10916373e-17  1.69176842e-16  3.75948537e-17
 -2.34967836e-16  1.69176842e-16 -1.31581988e-16 -1.12784561e-16
  7.98890642e-17 -2.34967836e-18  2.39667193e-16  2.34967836e-17
  7.51897075e-17 -4.22942105e-17 -2.11471052e-16  8.45884209e-17
  7.04903508e-17 -2.02072339e-16 -1.17483918e-16 -3.28954970e-17
 -7.40148683e-17  2.11471052e-17 -3.75948537e-17  9.39871344e-18
  0.00000000e+00 -1.03385848e-16  7.51897075e-17 -4.69935672e-17
 -2.81961403e-17 -9.39871344e-17  0.00000000e+00  9.39871344e-17
 -1.12784561e-16 -6.10916373e-17  1.73876199e-16 -1.26882631e-16
 -1.40980702e-16  8.45884209e-17  1.69176842e-16  9.39871344e-18
  3.75948537e-17  3.75948537e-17  1.59778128e-16  4.69935672e-17
 -5.63922806e-17  9.39871344e-18 -2.06771696e-16 -7.51897075e-17
 -2.13820731e-16 -7.51897075e-17 -2.34967836e-17  9.39871344e-18
  3.05458187e-16 -4.46438888e-17 -9.39871344e-17  2.09121374e-16
 -1.87974269e-17 -1.08085205e-16  1.45680058e-16 -1.08085205e-16
  1.22183275e-16  1.87974269e-17 -5.63922806e-17  9.39871344e-18
  0.00000000e+00 -9.39871344e-18  2.81961403e-17  6.57909941e-17
  0.00000000e+00  0.00000000e+00  1.87974269e-17 -1.40980702e-17
  4.69935672e-18  0.00000000e+00  0.00000000e+00 -8.22387426e-18
  9.39871344e-18  1.40980702e-17  9.39871344e-18 -3.52451754e-18
  1.64477485e-17 -1.76225877e-17  7.04903508e-18  1.17483918e-17
 -2.34967836e-18 -9.39871344e-18 -2.34967836e-18 -8.22387426e-18
  0.00000000e+00 -1.05735526e-17  4.69935672e-18 -2.34967836e-18
  9.39871344e-18 -4.69935672e-18  9.39871344e-18  2.11471052e-17
  1.29232310e-17 -4.69935672e-18 -1.58603289e-17  1.64477485e-17
  9.39871344e-18 -2.81961403e-17 -2.93709795e-18 -3.52451754e-17
 -1.05735526e-17 -3.75948537e-17 -9.39871344e-18 -1.87974269e-17
  4.93432455e-17  2.34967836e-18 -1.87974269e-17 -3.52451754e-17
  9.39871344e-18 -2.81961403e-17 -1.87974269e-17 -2.11471052e-17
 -6.57909941e-17 -8.69380993e-17  8.22387426e-18  1.03385848e-16
  1.03385848e-16 -1.73876199e-16 -1.17483918e-16  1.36281345e-16
 -2.39667193e-16 -5.87419590e-17 -1.55078772e-16 -5.16929239e-17
 -1.64477485e-17  4.22942105e-17  3.75948537e-17 -9.39871344e-18
 -5.16929239e-17  6.81406724e-17  4.69935672e-17 -1.40980702e-17
 -8.22387426e-17  1.87974269e-17 -4.69935672e-17 -7.98890642e-17
 -5.63922806e-17]
Std after scaling: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [63]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [67]:
# y should stay as it is
y = df['gender']   # or status

In [87]:
print(y_train[:10])
print(y_train.dtype)

212    0.73799
69     0.72199
329    0.74535
131    0.75399
44     0.76570
70     0.76904
407    0.56678
215    0.68983
409    0.82139
377    0.67408
Name: DFA, dtype: float64
float64

In [91]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['gender'])   # or df['status']

In [93]:
X = df.drop(['id', 'gender'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [95]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [97]:
from sklearn.svm import SVC

model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(kernel='linear')

In [99]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9144736842105263
              precision    recall  f1-score   support

           0       0.91      0.92      0.92        76
           1       0.92      0.91      0.91        76

    accuracy                           0.91       152
   macro avg       0.91      0.91      0.91       152
weighted avg       0.91      0.91      0.91       152

In [101]:
sample = X_scaled[0].reshape(1, -1)
prediction = model.predict(sample)

if prediction[0] == 1:
    print("Parkinson's Disease Detected")
else:
    print("Healthy Person")

Parkinson's Disease Detected

In [103]:
index = 5   # you can change this index

sample = X_test[index].reshape(1, -1)
prediction = model.predict(sample)

print("Prediction:", prediction[0])

if prediction[0] == 1:
    print("Result: Parkinson's Disease Detected")
else:
    print("Result: Healthy Person")

Prediction: 1
Result: Parkinson's Disease Detected